/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExtComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLExtComponentElement extends Components.ExtComponent, HTMLStencilElement {
    }
    var HTMLExtComponentElement: {
        prototype: HTMLExtComponentElement;
        new (): HTMLExtComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ext-component": HTMLExtComponentElement;
    }
}
declare namespace LocalJSX {
    interface ExtComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface IntrinsicElements {
        "ext-component": ExtComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ext-component": LocalJSX.ExtComponent & JSXBase.HTMLAttributes<HTMLExtComponentElement>;
        }
    }
}
